#!/usr/bin/env ruby

require "JSON"

def colorize(value, color)
	case color
		when :black then "\e[30m" + value.to_s + "\e[0m"
		when :red then "\e[31m" + value.to_s + "\e[0m"
		when :green then "\e[32m" + value.to_s + "\e[0m"
		when :yellow then "\e[33m" + value.to_s + "\e[0m"
		when :blue then "\e[34m" + value.to_s + "\e[0m"
		when :magenta then "\e[35m" + value.to_s + "\e[0m"
		when :cyan then "\e[36m" + value.to_s + "\e[0m"
		when :white then "\e[37m" + value.to_s + "\e[0m"
		when :bright_black then "\e[1m\e[30m" + value.to_s + "\e[0m"
		when :bright_red then "\e[1m\e[31m" + value.to_s + "\e[0m"
		when :bright_green then "\e[1m\e[32m" + value.to_s + "\e[0m"
		when :bright_yellow then "\e[1m\e[33m" + value.to_s + "\e[0m"
		when :bright_blue then "\e[1m\e[34m" + value.to_s + "\e[0m"
		when :bright_magenta then "\e[1m\e[35m" + value.to_s + "\e[0m"
		when :bright_cyan then "\e[1m\e[36m" + value.to_s + "\e[0m"
		when :bright_white then "\e[1m\e[37m" + value.to_s + "\e[0m"
		else value.to_s
	end
end

class PullRequest
  def initialize(id)
    @id = id
  end

  def title
    view["title"]
  end

  def created_by
    "#{view["author"]["login"]}"
  end

  def summary
    view["body"]
    .gsub(/[[:space:]]+/, ' ')
      .match(%r{What\'s this PR do\?(?<summary>.*?)\#}) {|m| m[:summary] }
  end

  def view
    @view ||= JSON.parse(%x{gh pr view #{@id} --json author,body,title})
  end
end

puts "Summarising pull requests for #{ARGV[0]}"

comparison = JSON.parse `gh api repos/{owner}/{repo}/compare/#{ARGV[0]}`

commits = comparison["commits"]

pull_request_ids = commits.filter_map do |commit|
  commit.dig("commit", "message")&.match(%r{Merge pull request #(?<id>[0-9]+) from}) {|m| m[:id]}
end

pull_requests = pull_request_ids.map do |id|
  PullRequest.new(id)
end

puts "#{colorize(pull_requests.count, :green)} merged pull requests found"

pull_requests.each.with_index(1) do |pull_request, index|
  puts "#{colorize(pull_request.title, :magenta)}"
  puts "#{pull_request.summary.nil? ? "No summary found" : pull_request.summary}"
  puts ""
end
